spring:
  application:
    name: msj-order
  datasource:
    url: jdbc:mysql://47.99.189.242:3306/meishijia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Ll-19921015
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: msj-order
server:
  port: 9104
feign:
  hystrix:
    #使断路器起作用
    enabled: true